### PR TITLE
fixed selector for shadow dom

### PR DESCRIPTION
**Pull request by uf0**

### CODE REVIEW

**Comment by lbolla** [comment]
@uf0 can you please explain what this patch is about?

**Comment by uf0** [comment]
Hi, 

this selector:
https://github.com/lbolla/fuckrep/blob/4dacbdaa3d46c4ffd33b27a1df53484084e430ef/fuckrep.js#L11
will always fail because the div `.detail-article_body` is inside the shadow dom.

So the result will look like this:
Screen Shot 2019-07-16 at 09 06 01

which is a bit _unreadable_ 😊

This selector should work:
https://github.com/uf0/fuckrep/blob/bf917b8ca53d867c26a35c0162a9886153c8d411/fuckrep.js#L19-L25

furthermore I noticed (but maybe it was already like this) that the full content is already loaded in this div but it has `display:none` :
https://github.com/uf0/fuckrep/blob/bf917b8ca53d867c26a35c0162a9886153c8d411/fuckrep.js#L13-L17

so it could be enough to modify the `display` property on both divs:
https://github.com/uf0/fuckrep/blob/bf917b8ca53d867c26a35c0162a9886153c8d411/fuckrep.js#L27-L28

without adding the content coming from the `content.json`:
https://github.com/uf0/fuckrep/blob/bf917b8ca53d867c26a35c0162a9886153c8d411/fuckrep.js#L29

as of now, I load the content coming from `content.json` but I leave in the PR all the code needed if you want to switch strategy and playing just with the `display` property.
In any case I think you should update the selector of the `.detail-article_body` div

**Comment by lbolla** [comment]
Unfortunately, I can't release a new version until https://discourse.mozilla.org/t/new-user-created-when-changing-email-in-github/42635 is fixed.

**Comment by lbolla** [comment]
Released as FuckRep2: https://addons.mozilla.org/en-GB/firefox/addon/fuckrep2/?src=search

**Pull request merged**
